# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:cpick/hub; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y update && sudo apt-get -y install hub; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install hub; fi
- echo "github.com:" > ~/.config/hub
- echo "- user: $GITHUB_USER" >> ~/.config/hub
- echo "  oauth_token: $GITHUB_TOKEN" >> ~/.config/hub
- echo "  protocol: https" >> ~/.config/hub
install:
- Rscript -e 'if (!require("rmarkdown")) install.packages("rmarkdown", repos = "https://cran.rstudio.org")'
script:
- Rscript -e 'rmarkdown::render("01_dependencies.R")'
- Rscript -e 'rmarkdown::render("02_create.R")'
- Rscript -e 'rmarkdown::render("03_build.R")'
