# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
addons:
  apt:
    update: true
    packages:
    - hub
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install hub; fi
install:
- Rscript -e 'if (!require("rmarkdown")) install.packages("rmarkdown", repos = "https://cran.rstudio.org")'
script:
- Rscript -e 'rmarkdown::render("01_dependencies.R")'
- Rscript -e 'rmarkdown::render("02_create.R")'
- Rscript -e 'rmarkdown::render("03_build.R")'
